#:kivy 2.3.0

AppManager:
    HomeScreen:

<HomeScreen>:
    name: "home"

    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "Percentage Calculator"

        MDBoxLayout:
            orientation: "vertical"
            padding: "20dp"
            spacing: "20dp"

            MDTextField:
                id: amount
                hint_text: "Amount"
                mode: "outlined"

            MDTextField:
                id: percent
                hint_text: "Percentage"
                mode: "outlined"

            MDRaisedButton:
                text: "Calculate"
                pos_hint: {"center_x": .5}
                on_release: root.calculate()

            MDLabel:
                id: result
                text: "Result: 0"
                halign: "center"