#:kivy 2.3.0

AppManager:

<HomeScreen>:
    name: "home"

    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 20

        Label:
            text: "Percentage Calculator"
            font_size: 30

        TextInput:
            hint_text: "Amount"

        TextInput:
            hint_text: "Percentage"

        Button:
            text: "Calculate"

        Label:
            text: "Result"

<AppManager>:
    HomeScreen: